AppEnvioArtigos/AppEnvioArtigos/Models/Participante.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AppEnvioArtigos.Models
{
    public class Participante
    {
        public int ParticipanteID { get; set; }
        
        public string Nome { get; set; }

       
        [DataType(DataType.PhoneNumber, ErrorMessage = "Forneça o número do telefone no formato (000) 00000-0000")]
        public string Telefone { get; set; }

        
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public int NumInscricao { get; set; }
        
        [Display(Name = "Local De Participação")]
        public string LocalParticipacao { get; set; }
    
        
        public string Senha { get; set; }
        
        [Display(Name = "Repita a sua senha:")]
        public string RepitaSenha { get; set; }

        public  Endereco Endereco { get; set; }
        public  CartaoCredito CartaoCredito { get; set; }

        public virtual ICollection<Artigos> ArtigosEnviados { get; set; }


    }

}

AppEnvioArtigos/AppEnvioArtigos/Controllers/ParticipantesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppEnvioArtigos.DAL;
using AppEnvioArtigos.Models;

namespace AppEnvioArtigos.Controllers
{
    public class ParticipantesController : Controller
    {
        private ArtigosContext db = new ArtigosContext();

        // GET: Participantes
        public ActionResult Index()
        {
            
            return View(db.Participantes.ToList());
        }


        // GET: Participantes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Participantes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ParticipanteID,Nome,Telefone,Email,LocalParticipacao,Senha,RepitaSenha,Endereco,CartaoCredito")] Participante participante)
        {
            if (ModelState.IsValid)
            {
                using (db)
                {
                    Random NumInscricao = new Random();
                    var v = db.Participantes.Where(model => model.NumInscricao.Equals(NumInscricao));
                    for (int i = 0; v != null; i++)
                    {
                        NumInscricao.Next(1000, 2000);
                        v = db.Participantes.Where(model => model.NumInscricao.Equals(NumInscricao));
                    }
                    ViewBag.NumInscricao = NumInscricao;
                        db.Participantes.Add(participante);
                        db.SaveChanges();
                        return RedirectToAction("Index", "Home");
                }
              
            }

            return View(participante);
        }
        /*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ParticipanteId,Revisor,Nome,Telefone,Email,LocalParticipacao,Senha,RepitaSenha,Endereco,CartaoCredito")] Revisor revisor)
        {
            if (ModelState.IsValid)
            {
                db.Participantes.Add(revisor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(revisor);
        }
        */


        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "Email,Senha,RepitaSenha,Endereco,CartaoCredito")]Participante participante)
        {
            // esta action trata o post (login)
            if (ModelState.IsValid) //verifica se é válido
            {
                using (db)
                {
                    var v = db.Participantes.Where(a => a.Email.Equals(participante.Email) && participante.Senha.Equals(participante.Senha)).FirstOrDefault();
                    if (v != null)
                    {
                        Session["usuarioLogadoID"] = v.ParticipanteID.ToString();
                        Session["nomeUsuarioLogado"] = v.Email.ToString();
                        return RedirectToAction("Index", "Home");
                    }
                }
                    
                
            }
            return View(participante);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppEnvioArtigos/AppEnvioArtigos/Views/Participantes/Create.cshtml
@model  AppEnvioArtigos.Models.Participante

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Participante</h4>
    <hr />
    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LocalParticipacao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LocalParticipacao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LocalParticipacao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RepitaSenha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.RepitaSenha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RepitaSenha, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
        </div>
    </div>


    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.CartaoCredito, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CartaoCredito, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CartaoCredito, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" onclick="ConfirmarInscricao()" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    function ConfirmarInscricao() {
        alert("Inscrição Confirmada! \n" + "Seu Numero de inscrição é: " + @ViewBag.NumInscricao);
    }
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppEnvioArtigos/AppEnvioArtigos/Views/Participantes/Index.cshtml
@model IEnumerable<AppEnvioArtigos.Models.Participante>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocalParticipacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Senha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RepitaSenha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Endereco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CartaoCredito)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LocalParticipacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Senha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RepitaSenha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Endereco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CartaoCredito)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ParticipanteId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ParticipanteId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ParticipanteId })
        </td>
    </tr>
}

</table>

AppEnvioArtigos/AppEnvioArtigos/Views/Participantes/Login.cshtml
@model AppEnvioArtigos.Models.Participante

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
@using (Html.BeginForm())
{
    //cria a tag do formulário
    @Html.AntiForgeryToken() // previne o ataque CSRF
    @Html.ValidationSummary(true)
    if (@ViewBag.Message != null)
    {
        <div style="border:1px solid red">
            @ViewBag.Message
        </div>
    }
    <table>
        <tr>
            <td>@Html.LabelFor(model => model.Email)</td>
            <td>@Html.TextBoxFor(model => model.Email)</td>
            <td>@Html.ValidationMessageFor(model => model.Email)</td>
        </tr>
        <tr>
            <td> @Html.LabelFor(a => a.Senha)</td>
            <td> @Html.PasswordFor(a => a.Senha) </td>
            <td> @Html.ValidationMessageFor(a => a.Senha) </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Login" />
                <button>@Html.ActionLink("Cadastre-se", "Create", "Participantes")</button>
            </td>
            <td></td>

            
        </tr>
        
    </table>

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}